export const closingProgressData = [
  {
    id: 1,
    taskNo: "T-1",
    taskName: "Move to a Pipeline Code of 2 in BMS",
    taskStatus: "Completed",
    dealTeamMember: "Duane Burton",
    personnel: "Credit",
    fileType: ["media"],
    targetDate: "09.12.2024",
    lastUpdated: "09.12.2024",
    isLock: false,
  },
  {
    id: 2,
    taskNo: "T-2",
    taskName: "Place S&U file in the Deal Folder",
    taskStatus: "Not Started",
    dealTeamMember: "Duane Burton",
    personnel: "Credit",
    fileType: ["media", "document", "excel"],
    targetDate: "09.12.2024",
    lastUpdated: "09.12.2024",
    isLock: false,
  },
  {
    id: 3,
    taskNo: "T-3",
    taskName: "Move to a Pipeline Code of 2 in BMS",
    taskStatus: "In Progress",
    dealTeamMember: "Duane Burton",
    personnel: "Credit",
    fileType: ["excel"],
    targetDate: "09.12.2024",
    lastUpdated: "09.12.2024",
    isLock: true,
  },
];
export const dealsData = [
  {
    id: "1",
    name: "AEM Buyer, LLC",
    amount: 1000000.0,
    stages: [
      {
        id: 1,
        avatarUrl: "src/assets/icons/initial-closing-process.svg",
        badgeText: "8/10",
        name: "John Smith",
        date: "09.12.2024",
        title: "Initiate Closing Process",
        avatarBgColor: "#6887D8",
        badgeBgColor: "#68A1D8",
        isLastChild: false,
        tasks: [
          {
            id: 1,
            taskNo: "T-1",
            taskName: "Move to a Pipeline Code of 2 in BMS",
            taskStatus: "Completed",
            dealTeamMember: "Duane Burton",
            personnel: "Credit",
            fileType: ["document"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: false,
            isLock: false,
            isInProgress: false,
          },
          {
            id: 2,
            taskNo: "T-2",
            taskName: "Place S&U file in the Deal Folder",
            taskStatus: "In Progress",
            dealTeamMember: "Duane Burton",
            personnel: "Credit",
            fileType: ["document", "excel"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: true,
            isLock: false,
            isInProgress: false,
          },
          {
            id: 3,
            taskNo: "T-3",
            taskName: "Engage Closing Team via Email to assign closers",
            taskStatus: "Not Started",
            dealTeamMember: "Duane Burton",
            personnel: "Credit",
            fileType: ["email"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: false,
            isInProgress: false,
            isLock: false,
          },
          {
            id: 4,
            taskNo: "T-4",
            taskName:
              "Engage Allocations Team via Email to assign allocations team",
            taskStatus: "Completed",
            dealTeamMember: "Helen Baxter",
            personnel: "Credit",
            fileType: ["email"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: false,
            isLock: false,
            isInProgress: true,
          },
          {
            id: 5,
            taskNo: "T-5",
            taskName:
              "Determine if Antares will facilitate communication / credit documentation",
            taskStatus: "Completed",
            dealTeamMember: "Matthew Melo",
            personnel: "Credit",
            fileType: ["document"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: true,
            isLock: false,
            isInProgress: false,
          },
          {
            id: 6,
            taskNo: "T-6",
            taskName: "Send Antares’ Counsel closing checklist items",
            taskStatus: "Completed",
            dealTeamMember: "Ronny Smith",
            personnel: "Credit",
            fileType: ["document"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: false,
            isLock: false,
            isInProgress: false,
          },
          {
            id: 7,
            taskNo: "T-7",
            taskName: "Send Checklist to Counsel",
            taskStatus: "Completed",
            dealTeamMember: "Gerardo Minton",
            personnel: "Credit",
            fileType: ["document"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: false,
            isLock: false,
            isInProgress: false,
          },
          {
            id: 8,
            taskNo: "T-8",
            taskName: "Include Antares Admin form to Antares Counsel",
            taskStatus: "Completed",
            dealTeamMember: "Duane Burton",
            personnel: "Credit",
            fileType: ["document", "excel"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: false,
            isLock: false,
            isInProgress: false,
          },
          {
            id: 9,
            taskNo: "T-9",
            taskName:
              "Confirm no updates to agent contact information with counsel",
            taskStatus: "Completed",
            dealTeamMember: "Helen Baxter",
            personnel: "Credit",
            fileType: ["document"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: false,
            isLock: false,
            isInProgress: false,
          },
          {
            id: 10,
            taskNo: "T-10",
            taskName: "Receive Antares Admin details and W9s/W8s from closing",
            taskStatus: "Completed",
            dealTeamMember: "David Brown",
            personnel: "Credit",
            fileType: ["document", "media", "excel"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: false,
            isLock: false,
            isInProgress: false,
          },
        ],
      },
      {
        id: 2,
        avatarUrl: "src/assets/icons/aml-kyc.svg",
        badgeText: "5/5",
        name: "Jane Smith",
        date: "09.15.2024",
        title: "AML / KYC",
        avatarBgColor: "#3D5063",
        badgeBgColor: "#68A1D8",
        isLastChild: false,
        tasks: [
          {
            id: 1,
            taskNo: "T-1",
            taskName: "Receive W9s/W8s for Equity Entity",
            taskStatus: "Completed",
            dealTeamMember: "Duane Burton",
            personnel: "Sponsor/Counsel",
            fileType: ["document"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: false,
            isLock: false,
          },
          {
            id: 2,
            taskNo: "T-2",
            taskName: "Receive Good Standing Certificate for the Equity Entity",
            taskStatus: "Completed",
            dealTeamMember: "Matthew Melo",
            personnel: "Sponsor/Counsel",
            fileType: ["document", "media"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: false,
            isLock: false,
          },
          {
            id: 3,
            taskNo: "T-3",
            taskName: "Receive Formation Documents for Equity Entity",
            taskStatus: "Completed",
            dealTeamMember: "Gerardo Minton",
            personnel: "Sponsor/Counsel",
            fileType: ["document", "excel"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: false,
            isLock: false,
          },
          {
            id: 4,
            taskNo: "T-4",
            taskName:
              "Receive List of all Board Members (please include Full Names)",
            taskStatus: "Completed",
            dealTeamMember: "Helen Baxter",
            personnel: "Sponsor/Counsel",
            fileType: ["document", "media", "excel"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: false,
            isLock: false,
          },
          {
            id: 5,
            taskNo: "T-5",
            taskName: "Receive Antares Equity Tag Checklist",
            taskStatus: "Completed",
            dealTeamMember: "Duane Burton",
            personnel: "Sponsor/Counsel",
            fileType: ["document", "media"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: false,
            isLock: false,
          },
        ],
      },
      {
        id: 3,
        avatarUrl: "src/assets/icons/antares-workflow.svg",
        badgeText: "7/7",
        name: "Jane Smith",
        date: "09.17.2024",
        title: "Antares Workflow",
        avatarBgColor: "#958B89",
        badgeBgColor: "#68A1D8",
        isLastChild: false,
        tasks: [
          {
            id: 1,
            taskNo: "T-1",
            taskName: "Complete Day 1 Expenses in S&U File",
            taskStatus: "Completed",
            dealTeamMember: "Duane Burton",
            personnel: "Credit",
            fileType: ["document"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: false,
            isLock: false,
            isInProgress: false,
          },
          {
            id: 2,
            taskNo: "T-2",
            taskName: "Receive draft Funds flow from Sponsor",
            taskStatus: "In Progress",
            dealTeamMember: "Duane Burton",
            personnel: "Credit",
            fileType: ["document", "excel"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: true,
            isLock: false,
            isInProgress: false,
          },
          {
            id: 3,
            taskNo: "T-3",
            taskName: "Finalize Covenant Model",
            taskStatus: "Not Started",
            dealTeamMember: "Duane Burton",
            personnel: "Credit",
            fileType: ["email"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: false,
            isInProgress: false,
            isLock: false,
          },
          {
            id: 4,
            taskNo: "T-3",
            taskName:
              "Push Closing Cash Flow Model into BMS (At Close approval type instead of Last Approved)",
            taskStatus: "Not Started",
            dealTeamMember: "Duane Burton",
            personnel: "Credit",
            fileType: ["email"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: false,
            isInProgress: false,
            isLock: false,
          },
          {
            id: 5,
            taskNo: "T-3",
            taskName:
              "Receive Allocations from Allocations team. These are uploaded to BMS. Pull down 'Allocations Details - Closing Memo and Docs' Report",
            taskStatus: "Not Started",
            dealTeamMember: "Duane Burton",
            personnel: "Credit",
            fileType: ["email"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: false,
            isInProgress: false,
            isLock: false,
          },
          {
            id: 6,
            taskNo: "T-6",
            taskName: "Finalize Covenant Model",
            taskStatus: "Not Started",
            dealTeamMember: "Duane Burton",
            personnel: "Credit",
            fileType: ["email"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: false,
            isInProgress: false,
            isLock: false,
          },
        ]
      }
      {
        id: 4,
        avatarUrl: "src/assets/icons/miscellaneous.svg",
        badgeText: "0/3",
        name: "",
        date: "",
        title: "Miscellaneous",
        avatarBgColor: "#FBAF3F",
        badgeBgColor: "#68A1D8",
        isLastChild: false,
        tasks: [
          {
            id: 1,
            taskNo: "T-1",
            taskName: "Move to a Pipeline Code of 2 in BMS",
            taskStatus: "Completed",
            dealTeamMember: "Duane Burton",
            personnel: "Credit",
            fileType: ["document"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: false,
            isLock: false,
            isInProgress: false,
          },
          {
            id: 2,
            taskNo: "T-2",
            taskName: "Place S&U file in the Deal Folder",
            taskStatus: "In Progress",
            dealTeamMember: "Duane Burton",
            personnel: "Credit",
            fileType: ["document", "excel"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: true,
            isLock: false,
            isInProgress: false,
          },
          {
            id: 3,
            taskNo: "T-3",
            taskName: "Engage Closing Team via Email to assign closers",
            taskStatus: "Not Started",
            dealTeamMember: "Duane Burton",
            personnel: "Credit",
            fileType: ["email"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: false,
            isInProgress: false,
            isLock: false,
          },
        ],
      },
      {
        id: 5,
        avatarUrl: "src/assets/icons/key-deliverables.svg",
        badgeText: "0/4",
        name: "",
        date: "",
        title: "Key Deliverables",
        avatarBgColor: "#3D5063",
        badgeBgColor: "#68A1D8",
        isLastChild: false,
        tasks: [
          {
            id: 1,
            taskNo: "T-1",
            taskName: "Move to a Pipeline Code of 2 in BMS",
            taskStatus: "Completed",
            dealTeamMember: "Duane Burton",
            personnel: "Credit",
            fileType: ["document"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: false,
            isLock: false,
            isInProgress: false,
          },
          {
            id: 2,
            taskNo: "T-2",
            taskName: "Place S&U file in the Deal Folder",
            taskStatus: "In Progress",
            dealTeamMember: "Duane Burton",
            personnel: "Credit",
            fileType: ["document", "excel"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: true,
            isLock: false,
            isInProgress: false,
          },
          {
            id: 3,
            taskNo: "T-3",
            taskName: "Engage Closing Team via Email to assign closers",
            taskStatus: "Not Started",
            dealTeamMember: "Duane Burton",
            personnel: "Credit",
            fileType: ["email"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: false,
            isInProgress: false,
            isLock: false,
          },
        ],
      },
      {
        id: 6,
        avatarUrl: "src/assets/icons/drafts.svg",
        badgeText: "0/4",
        name: "",
        date: "",
        title: "Drafts",
        avatarBgColor: "#428993",
        badgeBgColor: "#68A1D8",
        isLastChild: false,
        tasks: [
          {
            id: 1,
            taskNo: "T-1",
            taskName: "Move to a Pipeline Code of 2 in BMS",
            taskStatus: "Completed",
            dealTeamMember: "Duane Burton",
            personnel: "Credit",
            fileType: ["document"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: false,
            isLock: false,
            isInProgress: false,
          },
          {
            id: 2,
            taskNo: "T-2",
            taskName: "Place S&U file in the Deal Folder",
            taskStatus: "In Progress",
            dealTeamMember: "Duane Burton",
            personnel: "Credit",
            fileType: ["document", "excel"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: true,
            isLock: false,
            isInProgress: false,
          },
          {
            id: 3,
            taskNo: "T-3",
            taskName: "Engage Closing Team via Email to assign closers",
            taskStatus: "Not Started",
            dealTeamMember: "Duane Burton",
            personnel: "Credit",
            fileType: ["email"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: false,
            isInProgress: false,
            isLock: false,
          },
        ],
      },
      {
        id: 7,
        avatarUrl: "src/assets/icons/post-closing-items.svg",
        badgeText: "0/5",
        name: "",
        date: "",
        title: "Post-Closing Items",
        avatarBgColor: "#85556A",
        badgeBgColor: "#68A1D8",
        isLastChild: true,
        tasks: [
          {
            id: 1,
            taskNo: "T-1",
            taskName: "Move to a Pipeline Code of 2 in BMS",
            taskStatus: "Completed",
            dealTeamMember: "Duane Burton",
            personnel: "Credit",
            fileType: ["document"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: false,
            isLock: false,
            isInProgress: false,
          },
          {
            id: 2,
            taskNo: "T-2",
            taskName: "Place S&U file in the Deal Folder",
            taskStatus: "In Progress",
            dealTeamMember: "Duane Burton",
            personnel: "Credit",
            fileType: ["document", "excel"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: true,
            isLock: false,
            isInProgress: false,
          },
          {
            id: 3,
            taskNo: "T-3",
            taskName: "Engage Closing Team via Email to assign closers",
            taskStatus: "Not Started",
            dealTeamMember: "Duane Burton",
            personnel: "Credit",
            fileType: ["email"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: false,
            isInProgress: false,
            isLock: false,
          },
        ],
      },
    ],
  },
  {
    id: "2",
    name: "Capital Accord",
    amount: 50000.0,
    stages: [
      {
        id: 1,
        avatarUrl: "src/assets/icons/initial-closing-process.svg",
        badgeText: "8/10",
        name: "John Smith",
        date: "09.12.2024",
        title: "Initiate Closing Process",
        avatarBgColor: "#6887D8",
        badgeBgColor: "#68A1D8",
        isLastChild: false,
      },
      {
        id: 2,
        avatarUrl: "src/assets/icons/aml-kyc.svg",
        badgeText: "5/5",
        name: "Jane Smith",
        date: "09.15.2024",
        title: "AML / KYC",
        avatarBgColor: "#3D5063",
        badgeBgColor: "#68A1D8",
        isLastChild: false,
      },
      {
        id: 3,
        avatarUrl: "src/assets/icons/antares-workflow.svg",
        badgeText: "7/7",
        name: "",
        date: "09.17.2024",
        title: "Antares Workflow",
        avatarBgColor: "#958B89",
        badgeBgColor: "#68A1D8",
        isLastChild: false,
      },
      {
        id: 4,
        avatarUrl: "src/assets/icons/miscellaneous.svg",
        badgeText: "0/3",
        name: "",
        date: "",
        title: "Miscellaneous",
        avatarBgColor: "#FBAF3F",
        badgeBgColor: "#68A1D8",
        isLastChild: false,
      },
      {
        id: 5,
        avatarUrl: "src/assets/icons/key-deliverables.svg",
        badgeText: "0/4",
        name: "",
        date: "",
        title: "Key Deliverables",
        avatarBgColor: "#3D5063",
        badgeBgColor: "#68A1D8",
        isLastChild: false,
      },
      {
        id: 6,
        avatarUrl: "src/assets/icons/drafts.svg",
        badgeText: "0/4",
        name: "",
        date: "",
        title: "Drafts",
        avatarBgColor: "#428993",
        badgeBgColor: "#68A1D8",
        isLastChild: false,
      },
      {
        id: 7,
        avatarUrl: "src/assets/icons/post-closing-items.svg",
        badgeText: "0/5",
        name: "",
        date: "",
        title: "Post-Closing Items",
        avatarBgColor: "#85556A",
        badgeBgColor: "#68A1D8",
        isLastChild: true,
      },
    ],
    tasks: [
      {
        id: 1,
        taskNo: "T-1",
        taskName: "Move to a Pipeline Code of 2 in BMS",
        taskStatus: "Completed",
        dealTeamMember: "Duane Burton",
        personnel: "Credit",
        fileType: ["media"],
        targetDate: "09.12.2024",
        lastUpdated: "09.12.2024",
        isLock: "false",
      },
      {
        id: 2,
        taskNo: "T-2",
        taskName: "Place S&U file in the Deal Folder",
        taskStatus: "Not Started",
        dealTeamMember: "Duane Burton",
        personnel: "Credit",
        fileType: ["media", "document", "excel"],
        targetDate: "09.12.2024",
        lastUpdated: "09.12.2024",
        isLock: "false",
      },
      {
        id: 3,
        taskNo: "T-3",
        taskName: "Move to a Pipeline Code of 2 in BMS",
        taskStatus: "In Progress",
        dealTeamMember: "Duane Burton",
        personnel: "Credit",
        fileType: ["excel"],
        targetDate: "09.12.2024",
        lastUpdated: "09.12.2024",
        isLock: "true",
      },
    ],
  },
  {
    id: "2",
    name: "Venture Accord",
    amount: 50000.0,
    stages: [
      {
        id: 1,
        avatarUrl: "src/assets/icons/initial-closing-process.svg",
        badgeText: "8/10",
        name: "John Smith",
        date: "09.12.2024",
        title: "Initiate Closing Process",
        avatarBgColor: "#6887D8",
        badgeBgColor: "#68A1D8",
        isLastChild: false,
      },
      {
        id: 2,
        avatarUrl: "src/assets/icons/aml-kyc.svg",
        badgeText: "5/5",
        name: "Jane Smith",
        date: "09.15.2024",
        title: "AML / KYC",
        avatarBgColor: "#3D5063",
        badgeBgColor: "#68A1D8",
        isLastChild: false,
      },
      {
        id: 3,
        avatarUrl: "src/assets/icons/antares-workflow.svg",
        badgeText: "7/7",
        name: "",
        date: "09.17.2024",
        title: "Antares Workflow",
        avatarBgColor: "#958B89",
        badgeBgColor: "#68A1D8",
        isLastChild: false,
      },
      {
        id: 4,
        avatarUrl: "src/assets/icons/miscellaneous.svg",
        badgeText: "0/3",
        name: "",
        date: "",
        title: "Miscellaneous",
        avatarBgColor: "#FBAF3F",
        badgeBgColor: "#68A1D8",
        isLastChild: false,
      },
      {
        id: 5,
        avatarUrl: "src/assets/icons/key-deliverables.svg",
        badgeText: "0/4",
        name: "",
        date: "",
        title: "Key Deliverables",
        avatarBgColor: "#3D5063",
        badgeBgColor: "#68A1D8",
        isLastChild: false,
      },
      {
        id: 6,
        avatarUrl: "src/assets/icons/drafts.svg",
        badgeText: "0/4",
        name: "",
        date: "",
        title: "Drafts",
        avatarBgColor: "#428993",
        badgeBgColor: "#68A1D8",
        isLastChild: false,
      },
      {
        id: 7,
        avatarUrl: "src/assets/icons/post-closing-items.svg",
        badgeText: "0/5",
        name: "",
        date: "",
        title: "Post-Closing Items",
        avatarBgColor: "#85556A",
        badgeBgColor: "#68A1D8",
        isLastChild: true,
      },
    ],
    tasks: [
      {
        id: 1,
        taskNo: "T-1",
        taskName: "Move to a Pipeline Code of 2 in BMS",
        taskStatus: "Completed",
        dealTeamMember: "Duane Burton",
        personnel: "Credit",
        fileType: ["media"],
        targetDate: "09.12.2024",
        lastUpdated: "09.12.2024",
        isLock: "false",
      },
      {
        id: 2,
        taskNo: "T-2",
        taskName: "Place S&U file in the Deal Folder",
        taskStatus: "Not Started",
        dealTeamMember: "Duane Burton",
        personnel: "Credit",
        fileType: ["media", "document", "excel"],
        targetDate: "09.12.2024",
        lastUpdated: "09.12.2024",
        isLock: "false",
      },
      {
        id: 3,
        taskNo: "T-3",
        taskName: "Move to a Pipeline Code of 2 in BMS",
        taskStatus: "In Progress",
        dealTeamMember: "Duane Burton",
        personnel: "Credit",
        fileType: ["excel"],
        targetDate: "09.12.2024",
        lastUpdated: "09.12.2024",
        isLock: "true",
      },
    ],
  },
];
export const myWorkDealsData = [
  {
    id: "1",
    name: "AEM Buyer, LLC",
    amount: 1000000.0,
    stages: [
      {
        id: 1,
        avatarUrl: "src/assets/icons/initial-closing-process.svg",
        badgeText: "8/10",
        name: "John Smith",
        date: "09.12.2024",
        title: "Initiate Closing Process",
        avatarBgColor: "#6887D8",
        badgeBgColor: "#68A1D8",
        isLastChild: false,
        tasks: [
          {
            id: 1,
            taskNo: "T-1",
            taskName: "Move to a Pipeline Code of 2 in BMS",
            taskStatus: "Completed",
            dealTeamMember: "Duane Burton",
            personnel: "Credit",
            fileType: ["document"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: false,
            isLock: false,
            isInProgress: false,
          },
          {
            id: 2,
            taskNo: "T-2",
            taskName: "Place S&U file in the Deal Folder",
            taskStatus: "In Progress",
            dealTeamMember: "Duane Burton",
            personnel: "Credit",
            fileType: ["document", "excel"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: true,
            isLock: false,
            isInProgress: false,
          },
          {
            id: 3,
            taskNo: "T-3",
            taskName: "Engage Closing Team via Email to assign closers",
            taskStatus: "Not Started",
            dealTeamMember: "Duane Burton",
            personnel: "Credit",
            fileType: ["email"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: false,
            isInProgress: false,
            isLock: false,
          },
        ],
      },
      {
        id: 2,
        avatarUrl: "src/assets/icons/aml-kyc.svg",
        badgeText: "5/5",
        name: "Jane Smith",
        date: "09.15.2024",
        title: "AML / KYC",
        avatarBgColor: "#3D5063",
        badgeBgColor: "#68A1D8",
        isLastChild: false,
        tasks: [
          {
            id: 1,
            taskNo: "T-1",
            taskName: "Move to a Pipeline Code of 2 in BMS",
            taskStatus: "Completed",
            dealTeamMember: "Duane Burton",
            personnel: "Credit",
            fileType: ["document"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: false,
            isLock: false,
            isInProgress: false,
          },
          {
            id: 2,
            taskNo: "T-2",
            taskName: "Place S&U file in the Deal Folder",
            taskStatus: "In Progress",
            dealTeamMember: "Duane Burton",
            personnel: "Credit",
            fileType: ["document", "excel"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: true,
            isLock: false,
            isInProgress: false,
          },
          {
            id: 3,
            taskNo: "T-3",
            taskName: "Engage Closing Team via Email to assign closers",
            taskStatus: "Not Started",
            dealTeamMember: "Duane Burton",
            personnel: "Credit",
            fileType: ["email"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: false,
            isInProgress: false,
            isLock: false,
          },
        ],
      },
      {
        id: 3,
        avatarUrl: "src/assets/icons/antares-workflow.svg",
        badgeText: "7/7",
        name: "Jane Smith",
        date: "09.17.2024",
        title: "Antares Workflow",
        avatarBgColor: "#958B89",
        badgeBgColor: "#68A1D8",
        isLastChild: false,
        tasks: [
          {
            id: 1,
            taskNo: "T-1",
            taskName: "Move to a Pipeline Code of 2 in BMS",
            taskStatus: "Completed",
            dealTeamMember: "Duane Burton",
            personnel: "Credit",
            fileType: ["document"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: false,
            isLock: false,
            isInProgress: false,
          },
          {
            id: 2,
            taskNo: "T-2",
            taskName: "Place S&U file in the Deal Folder",
            taskStatus: "In Progress",
            dealTeamMember: "Duane Burton",
            personnel: "Credit",
            fileType: ["document", "excel"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: true,
            isLock: false,
            isInProgress: false,
          },
          {
            id: 3,
            taskNo: "T-3",
            taskName: "Engage Closing Team via Email to assign closers",
            taskStatus: "Not Started",
            dealTeamMember: "Duane Burton",
            personnel: "Credit",
            fileType: ["email"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: false,
            isInProgress: false,
            isLock: false,
          },
        ],
      },
      {
        id: 4,
        avatarUrl: "src/assets/icons/drafts.svg",
        badgeText: "0/4",
        name: "",
        date: "",
        title: "Drafts",
        avatarBgColor: "#428993",
        badgeBgColor: "#68A1D8",
        isLastChild: false,
        tasks: [
          {
            id: 1,
            taskNo: "T-1",
            taskName: "Move to a Pipeline Code of 2 in BMS",
            taskStatus: "Completed",
            dealTeamMember: "Duane Burton",
            personnel: "Credit",
            fileType: ["document"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: false,
            isLock: false,
            isInProgress: false,
          },
          {
            id: 2,
            taskNo: "T-2",
            taskName: "Place S&U file in the Deal Folder",
            taskStatus: "In Progress",
            dealTeamMember: "Duane Burton",
            personnel: "Credit",
            fileType: ["document", "excel"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: true,
            isLock: false,
            isInProgress: false,
          },
          {
            id: 3,
            taskNo: "T-3",
            taskName: "Engage Closing Team via Email to assign closers",
            taskStatus: "Not Started",
            dealTeamMember: "Duane Burton",
            personnel: "Credit",
            fileType: ["email"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: false,
            isInProgress: false,
            isLock: false,
          },
        ],
      },
      {
        id: 5,
        avatarUrl: "src/assets/icons/post-closing-items.svg",
        badgeText: "0/5",
        name: "",
        date: "",
        title: "Post-Closing Items",
        avatarBgColor: "#85556A",
        badgeBgColor: "#68A1D8",
        isLastChild: true,
        tasks: [
          {
            id: 1,
            taskNo: "T-1",
            taskName: "Move to a Pipeline Code of 2 in BMS",
            taskStatus: "Completed",
            dealTeamMember: "Duane Burton",
            personnel: "Credit",
            fileType: ["document"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: false,
            isLock: false,
            isInProgress: false,
          },
          {
            id: 2,
            taskNo: "T-2",
            taskName: "Place S&U file in the Deal Folder",
            taskStatus: "In Progress",
            dealTeamMember: "Duane Burton",
            personnel: "Credit",
            fileType: ["document", "excel"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: true,
            isLock: false,
            isInProgress: false,
          },
          {
            id: 3,
            taskNo: "T-3",
            taskName: "Engage Closing Team via Email to assign closers",
            taskStatus: "Not Started",
            dealTeamMember: "Duane Burton",
            personnel: "Credit",
            fileType: ["email"],
            targetDate: "09.12.2024",
            lastUpdated: "09.12.2024",
            isSetting: false,
            isInProgress: false,
            isLock: false,
          },
        ],
      },
    ],
  },
  {
    id: "2",
    name: "Capital Accord",
    amount: 50000.0,
    stages: [
      {
        id: 1,
        avatarUrl: "src/assets/icons/initial-closing-process.svg",
        badgeText: "8/10",
        name: "John Smith",
        date: "09.12.2024",
        title: "Initiate Closing Process",
        avatarBgColor: "#6887D8",
        badgeBgColor: "#68A1D8",
        isLastChild: false,
      },
      {
        id: 2,
        avatarUrl: "src/assets/icons/aml-kyc.svg",
        badgeText: "5/5",
        name: "Jane Smith",
        date: "09.15.2024",
        title: "AML / KYC",
        avatarBgColor: "#3D5063",
        badgeBgColor: "#68A1D8",
        isLastChild: false,
      },
      {
        id: 3,
        avatarUrl: "src/assets/icons/antares-workflow.svg",
        badgeText: "7/7",
        name: "",
        date: "09.17.2024",
        title: "Antares Workflow",
        avatarBgColor: "#958B89",
        badgeBgColor: "#68A1D8",
        isLastChild: false,
      },
      {
        id: 4,
        avatarUrl: "src/assets/icons/drafts.svg",
        badgeText: "0/4",
        name: "",
        date: "",
        title: "Drafts",
        avatarBgColor: "#428993",
        badgeBgColor: "#68A1D8",
        isLastChild: false,
      },
      {
        id: 5,
        avatarUrl: "src/assets/icons/post-closing-items.svg",
        badgeText: "0/5",
        name: "",
        date: "",
        title: "Post-Closing Items",
        avatarBgColor: "#85556A",
        badgeBgColor: "#68A1D8",
        isLastChild: true,
      },
    ],
    tasks: [
      {
        id: 1,
        taskNo: "T-1",
        taskName: "Move to a Pipeline Code of 2 in BMS",
        taskStatus: "Completed",
        dealTeamMember: "Duane Burton",
        personnel: "Credit",
        fileType: ["media"],
        targetDate: "09.12.2024",
        lastUpdated: "09.12.2024",
        isLock: "false",
      },
      {
        id: 2,
        taskNo: "T-2",
        taskName: "Place S&U file in the Deal Folder",
        taskStatus: "Not Started",
        dealTeamMember: "Duane Burton",
        personnel: "Credit",
        fileType: ["media", "document", "excel"],
        targetDate: "09.12.2024",
        lastUpdated: "09.12.2024",
        isLock: "false",
      },
      {
        id: 3,
        taskNo: "T-3",
        taskName: "Move to a Pipeline Code of 2 in BMS",
        taskStatus: "In Progress",
        dealTeamMember: "Duane Burton",
        personnel: "Credit",
        fileType: ["excel"],
        targetDate: "09.12.2024",
        lastUpdated: "09.12.2024",
        isLock: "true",
      },
    ],
  },
  {
    id: "2",
    name: "Venture Accord",
    amount: 50000.0,
    stages: [
      {
        id: 1,
        avatarUrl: "src/assets/icons/initial-closing-process.svg",
        badgeText: "8/10",
        name: "John Smith",
        date: "09.12.2024",
        title: "Initiate Closing Process",
        avatarBgColor: "#6887D8",
        badgeBgColor: "#68A1D8",
        isLastChild: false,
      },
      {
        id: 2,
        avatarUrl: "src/assets/icons/aml-kyc.svg",
        badgeText: "5/5",
        name: "Jane Smith",
        date: "09.15.2024",
        title: "AML / KYC",
        avatarBgColor: "#3D5063",
        badgeBgColor: "#68A1D8",
        isLastChild: false,
      },
      {
        id: 3,
        avatarUrl: "src/assets/icons/antares-workflow.svg",
        badgeText: "7/7",
        name: "",
        date: "09.17.2024",
        title: "Antares Workflow",
        avatarBgColor: "#958B89",
        badgeBgColor: "#68A1D8",
        isLastChild: false,
      },
      {
        id: 4,
        avatarUrl: "src/assets/icons/drafts.svg",
        badgeText: "0/4",
        name: "",
        date: "",
        title: "Drafts",
        avatarBgColor: "#428993",
        badgeBgColor: "#68A1D8",
        isLastChild: false,
      },
      {
        id: 5,
        avatarUrl: "src/assets/icons/post-closing-items.svg",
        badgeText: "0/5",
        name: "",
        date: "",
        title: "Post-Closing Items",
        avatarBgColor: "#85556A",
        badgeBgColor: "#68A1D8",
        isLastChild: true,
      },
    ],
    tasks: [
      {
        id: 1,
        taskNo: "T-1",
        taskName: "Move to a Pipeline Code of 2 in BMS",
        taskStatus: "Completed",
        dealTeamMember: "Duane Burton",
        personnel: "Credit",
        fileType: ["media"],
        targetDate: "09.12.2024",
        lastUpdated: "09.12.2024",
        isLock: "false",
      },
      {
        id: 2,
        taskNo: "T-2",
        taskName: "Place S&U file in the Deal Folder",
        taskStatus: "Not Started",
        dealTeamMember: "Duane Burton",
        personnel: "Credit",
        fileType: ["media", "document", "excel"],
        targetDate: "09.12.2024",
        lastUpdated: "09.12.2024",
        isLock: "false",
      },
      {
        id: 3,
        taskNo: "T-3",
        taskName: "Move to a Pipeline Code of 2 in BMS",
        taskStatus: "In Progress",
        dealTeamMember: "Duane Burton",
        personnel: "Credit",
        fileType: ["excel"],
        targetDate: "09.12.2024",
        lastUpdated: "09.12.2024",
        isLock: "true",
      },
    ],
  },
];
